Map<String, String> arabicMap = {
  'Welcome to Good Doctor App': 'مرحبًا بكم في تطبيق الطبيب الجيد',
  'Your health, our priority': 'صحتك، أولويتنا',
  'Medical Record:': 'السجل الطبي:',
  'Medicine Taken:': 'الأدوية المتناولة:',
  'Status': 'الحالة',
  'Cancel': 'إلغاء',
  'Accept': 'قبول',
  'Doctor Specialization': 'تخصص الطبيب',
  'Medical Record': 'السجل الطبي',
  'Medicine Taken': 'الأدوية المتناولة',
  'Hi Dr.': 'مرحباً د.',
  'Hi Patient.': 'مرحباً مريض.',
  'Specialization:': 'التخصص:',
  'Accepted': 'مقبول',
  'Cancelled': 'ملغي',
  'Book': 'حجز',
  'If you aren\'t registered ?': 'إذا لم تكن مسجلا ؟',
  'Register Now': 'سجل الآن',
  'If you are registered ?': 'إذا كنت مسجلا ؟',
  'Login Now': 'تسجيل الدخول الآن',
  'Register': 'سجل',
  'Login': 'تسجيل الدخول',
  'Accepted - Book Again': 'مقبول - احجز مرة أخرى',
  'Cancelled by Doctor - Book Again':
      'تم الإلغاء بواسطة الطبيب - احجز مرة أخرى',
  'Please select a type': 'من فضلك اختر النوع',
  'First Name': 'الاسم الاول',
  'Second Name': 'الاسم الثاني',
  'Password': 'كلمة المرور',
  'Email': 'الايميل',
  'Doctor': 'طبيب',
  'Patient': 'مريض',
  'Sign Up': 'اشترك',
  'Log In': 'تسجيل الدخول',
  'this field is required': 'هذاالحقل مطلوب',
  'Password must be at least 8 characters':
      'كلمه المرور يجب ان تكون 8 احرف عل الاقل',
  'Status:': 'الحاله:',
};
