Map<String, String> englishMap = {
  'Welcome to Good Doctor App': 'Welcome to Good Doctor App',
  'Your health, our priority': 'Your health, our priority',
  'Medical Record:': 'Medical Record:',
  'Medicine Taken:': 'Medicine Taken:',
  'Status': 'Status',
  'Cancel': 'Cancel',
  'Accept': 'Accept',
  'Doctor Specialization': 'Doctor Specialization',
  'Medicine Taken': 'Medicine Taken',
  'Medical Record': 'Medical Record',
  'Hi Dr.': "Hi Dr.",
  'Hi Patient.': 'Hi Patient.',
  'Specialization:': 'Specialization:',
  'Accepted': 'Accepted',
  'Cancelled': 'Cancelled',
  'Book': 'Book',
  'If you aren\'t registered ?': 'If you aren\'t registered ?',
  'Register Now': 'Register Now',
  'If you are registered ?': 'If you are registered ?',
  'Register': 'Register',
  'Login': 'Login',
  'Accepted - Book Again': 'Accepted - Book Again',
  'Cancelled by Doctor - Book Again': 'Cancelled by Doctor - Book Again',
  'Please select a type': 'Please select a type',
  'First Name': 'First Name',
  'Second Name': 'Second Name',
  'Password': 'Password',
  'Doctor': 'Doctor',
  'Patient': 'Patient',
  'Sign Up': 'Sign Up',
  'Log In': 'Log In',
  'Email': 'Email',
  'this field is required': 'this field is required',
  'Password must be at least 8 characters':
      'Password must be at least 8 characters',
  'Status:': 'Status:',
};
