// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjLRHH6_LDpiFWgVxQdf4subnGvATjuA',
    appId: '1:535977460671:web:53ce4b6c5518e7515e570a',
    messagingSenderId: '535977460671',
    projectId: 'doctor-patient-firebase-app',
    authDomain: 'doctor-patient-firebase-app.firebaseapp.com',
    storageBucket: 'doctor-patient-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEEZ0CJ6Zuz95pFLITvOUUblaSMMuoaI',
    appId: '1:535977460671:android:9e704558809a5c8f5e570a',
    messagingSenderId: '535977460671',
    projectId: 'doctor-patient-firebase-app',
    storageBucket: 'doctor-patient-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlD0V6sbzHoW61K-jD3pOiDa-xQLzIHQ',
    appId: '1:535977460671:ios:440b7148219dbc215e570a',
    messagingSenderId: '535977460671',
    projectId: 'doctor-patient-firebase-app',
    storageBucket: 'doctor-patient-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.goodDoctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlD0V6sbzHoW61K-jD3pOiDa-xQLzIHQ',
    appId: '1:535977460671:ios:440b7148219dbc215e570a',
    messagingSenderId: '535977460671',
    projectId: 'doctor-patient-firebase-app',
    storageBucket: 'doctor-patient-firebase-app.firebasestorage.app',
    iosBundleId: 'com.example.goodDoctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtjLRHH6_LDpiFWgVxQdf4subnGvATjuA',
    appId: '1:535977460671:web:ba08b622ffc2367b5e570a',
    messagingSenderId: '535977460671',
    projectId: 'doctor-patient-firebase-app',
    authDomain: 'doctor-patient-firebase-app.firebaseapp.com',
    storageBucket: 'doctor-patient-firebase-app.firebasestorage.app',
  );
}
